/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.DAO_Configuracion;
import Model.Configuracion;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Jose_Gonzalez
 */
public class FrmDolar extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDolar
     */
    public FrmDolar() {
        initComponents();
        txtAnterior.setEnabled(false);
        valorAnterior();
    }
    
    public void valorAnterior() {
        DAO_Configuracion funcion = new DAO_Configuracion();
        float dolar = funcion.getValueDollar();
        txtAnterior.setText(""+dolar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAnterior = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNuevo = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 118, 210));
        jLabel10.setText("Actualizar costo del Dolar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 118, 210));
        jLabel1.setText("Costo Nuevo:        $");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 20));
        getContentPane().add(txtAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 118, 210));
        jLabel2.setText("Costo Anterior:    $");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 20));
        getContentPane().add(txtNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(25, 118, 210));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(25, 118, 210));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        DAO_Configuracion funcion = new DAO_Configuracion();
        try {
            MaskFormatter format = new MaskFormatter("##.##");
            JFormattedTextField txt = new JFormattedTextField(format);
            txt.setValue(new Float(txtNuevo.getText()));
           
            float nuevo = (float) txt.getValue();
            
            Configuracion conf = new Configuracion();
            conf.setValorDolar(nuevo);
            
            if (funcion.updateValueDollar(conf)) {
                JOptionPane.showMessageDialog(null, "Valor del Dolar Actualizado");
                valorAnterior();;
                txtNuevo.setText("");
            }
        } catch (Exception e) {
            System.err.println("Error:" + e);
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el valor");
            txtNuevo.setText("");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAnterior;
    private javax.swing.JTextField txtNuevo;
    // End of variables declaration//GEN-END:variables
}
