/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JPanel;
import Model.HistorialStock;
import Model.Producto;
import DAO.DAO_HistorialStock;
import DAO.DAO_Producto;
import java.awt.Component;
import java.sql.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose_Gonzalez
 */
public class FrmHistorialStock extends javax.swing.JFrame {

    /**
     * Creates new form FrmHistorialStock1
     */
    public FrmHistorialStock() {
        initComponents();
        
        jrbAumentar.setSelected(true);
        this.setLocationRelativeTo(null);
        txtUsu.setVisible(false);
        dcFecha.setVisible(false);
        txtCod_Producto.setEditable(false);
        txtProveedor.setEditable(false);
        txtPrecio.setEditable(false);
        txtExistencia.setEditable(false);
        Calendar c2 = new GregorianCalendar();
        dcFecha.setCalendar(c2);
                
        jTabla.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                l.setBackground(new java.awt.Color(255, 255, 255));
                l.setForeground(new java.awt.Color(0, 0, 0));
                l.setFont(new java.awt.Font("Dialog", 3, 14));
                return l;
            }
        });
    }
    
    public void mostrar(String id) {
        try {
            DefaultTableModel modelo;
            DAO_HistorialStock funcion = new DAO_HistorialStock();
            modelo = funcion.Mostrar(id);
            jTabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al agregar stock.");
        }
    }

    public void habilitar() {
        btnAceptarValores.setEnabled(true);
        txtValor.setEditable(true);
        txtPrecio.setText("");
        txtExistencia.setText("");
        txtValor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabla = jTabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jrbAumentar = new javax.swing.JRadioButton();
        jrbDisminuir = new javax.swing.JRadioButton();
        txtValor = new javax.swing.JTextField();
        btnAceptarValores = new javax.swing.JButton();
        lineaValor = new javax.swing.JPanel();
        jPanelVerde = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCod_Producto = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtExistencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lineaCodigo = new javax.swing.JPanel();
        lineaProveedor = new javax.swing.JPanel();
        lineaExistencia = new javax.swing.JPanel();
        lineaVenta = new javax.swing.JPanel();
        txtUsu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelMinimizar = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 139, 66)));
        jPanel2.setForeground(new java.awt.Color(25, 118, 210));
        jPanel2.setPreferredSize(new java.awt.Dimension(628, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabla.setGridColor(new java.awt.Color(204, 204, 204));
        jTabla.setRowHeight(20);
        jTabla.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTabla.setSelectionForeground(new java.awt.Color(0, 102, 0));
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTablaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTabla);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 608, 221));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 139, 66)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbAumentar.setBackground(new java.awt.Color(255, 255, 255));
        btnGroup.add(jrbAumentar);
        jrbAumentar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jrbAumentar.setText("Agregar");
        jPanel3.add(jrbAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 12, 96, 20));

        jrbDisminuir.setBackground(new java.awt.Color(255, 255, 255));
        btnGroup.add(jrbDisminuir);
        jrbDisminuir.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jrbDisminuir.setText("Disminuir");
        jPanel3.add(jrbDisminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 36, 96, 12));

        txtValor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtValor.setBorder(null);
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        jPanel3.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 17, 346, 23));

        btnAceptarValores.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptarValores.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAceptarValores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Views/guardar.png"))); // NOI18N
        btnAceptarValores.setText("Guardar");
        btnAceptarValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarValoresActionPerformed(evt);
            }
        });
        jPanel3.add(btnAceptarValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 12, 114, -1));

        lineaValor.setBackground(new java.awt.Color(153, 153, 153));
        lineaValor.setPreferredSize(new java.awt.Dimension(325, 2));

        javax.swing.GroupLayout lineaValorLayout = new javax.swing.GroupLayout(lineaValor);
        lineaValor.setLayout(lineaValorLayout);
        lineaValorLayout.setHorizontalGroup(
            lineaValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        lineaValorLayout.setVerticalGroup(
            lineaValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel3.add(lineaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 40, 346, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 600, 70));

        jPanelVerde.setBackground(new java.awt.Color(65, 139, 66));
        jPanelVerde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(65, 139, 66));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Codigo :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Proveedor :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 52, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Existencia :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 93, -1, -1));

        txtCod_Producto.setBackground(new java.awt.Color(65, 139, 66));
        txtCod_Producto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCod_Producto.setForeground(new java.awt.Color(255, 255, 255));
        txtCod_Producto.setText(" ");
        txtCod_Producto.setBorder(null);
        txtCod_Producto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCod_Producto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCod_ProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCod_ProductoFocusLost(evt);
            }
        });
        jPanel4.add(txtCod_Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 11, 444, -1));

        txtProveedor.setBackground(new java.awt.Color(65, 139, 66));
        txtProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtProveedor.setText(" ");
        txtProveedor.setBorder(null);
        txtProveedor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProveedorFocusLost(evt);
            }
        });
        jPanel4.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 52, 444, -1));

        txtPrecio.setBackground(new java.awt.Color(65, 139, 66));
        txtPrecio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setBorder(null);
        txtPrecio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        jPanel4.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 129, 444, -1));

        txtExistencia.setBackground(new java.awt.Color(65, 139, 66));
        txtExistencia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtExistencia.setForeground(new java.awt.Color(255, 255, 255));
        txtExistencia.setBorder(null);
        txtExistencia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtExistencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtExistenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExistenciaFocusLost(evt);
            }
        });
        jPanel4.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 93, 444, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Venta :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 129, -1, -1));

        lineaCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lineaCodigo.setPreferredSize(new java.awt.Dimension(325, 2));

        javax.swing.GroupLayout lineaCodigoLayout = new javax.swing.GroupLayout(lineaCodigo);
        lineaCodigo.setLayout(lineaCodigoLayout);
        lineaCodigoLayout.setHorizontalGroup(
            lineaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        lineaCodigoLayout.setVerticalGroup(
            lineaCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(lineaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 30, 444, 2));

        lineaProveedor.setBackground(new java.awt.Color(255, 255, 255));
        lineaProveedor.setPreferredSize(new java.awt.Dimension(325, 2));

        javax.swing.GroupLayout lineaProveedorLayout = new javax.swing.GroupLayout(lineaProveedor);
        lineaProveedor.setLayout(lineaProveedorLayout);
        lineaProveedorLayout.setHorizontalGroup(
            lineaProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        lineaProveedorLayout.setVerticalGroup(
            lineaProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(lineaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 70, 444, -1));

        lineaExistencia.setBackground(new java.awt.Color(255, 255, 255));
        lineaExistencia.setPreferredSize(new java.awt.Dimension(325, 2));

        javax.swing.GroupLayout lineaExistenciaLayout = new javax.swing.GroupLayout(lineaExistencia);
        lineaExistencia.setLayout(lineaExistenciaLayout);
        lineaExistenciaLayout.setHorizontalGroup(
            lineaExistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        lineaExistenciaLayout.setVerticalGroup(
            lineaExistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(lineaExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 111, 444, -1));

        lineaVenta.setBackground(new java.awt.Color(255, 255, 255));
        lineaVenta.setPreferredSize(new java.awt.Dimension(325, 2));

        javax.swing.GroupLayout lineaVentaLayout = new javax.swing.GroupLayout(lineaVenta);
        lineaVenta.setLayout(lineaVentaLayout);
        lineaVentaLayout.setHorizontalGroup(
            lineaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        lineaVentaLayout.setVerticalGroup(
            lineaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(lineaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 147, 444, -1));

        jPanelVerde.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuActionPerformed(evt);
            }
        });
        jPanelVerde.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 39, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("STOCK DE PRODUCTOS");
        jPanelVerde.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        dcFecha.setBackground(new java.awt.Color(36, 33, 33));
        dcFecha.setForeground(new java.awt.Color(207, 207, 207));
        dcFecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanelVerde.add(dcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 44, -1));

        jPanelCerrar.setBackground(new java.awt.Color(65, 139, 66));

        jLabelCerrar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCerrarLayout = new javax.swing.GroupLayout(jPanelCerrar);
        jPanelCerrar.setLayout(jPanelCerrarLayout);
        jPanelCerrarLayout.setHorizontalGroup(
            jPanelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCerrarLayout.setVerticalGroup(
            jPanelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelVerde.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 0, 20, 18));

        jPanelMinimizar.setBackground(new java.awt.Color(65, 139, 66));

        btnMinimizar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setText("_");
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizarLayout = new javax.swing.GroupLayout(jPanelMinimizar);
        jPanelMinimizar.setLayout(jPanelMinimizarLayout);
        jPanelMinimizarLayout.setHorizontalGroup(
            jPanelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(jPanelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMinimizarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelMinimizarLayout.setVerticalGroup(
            jPanelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
            .addGroup(jPanelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMinimizarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelVerde.add(jPanelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 20, 18));

        jPanel2.add(jPanelVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 628, 230));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked

    }//GEN-LAST:event_jTablaMouseClicked

    private void jTablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMousePressed

    }//GEN-LAST:event_jTablaMousePressed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed

    }//GEN-LAST:event_txtValorKeyPressed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    private void btnAceptarValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarValoresActionPerformed

        if (txtValor.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar el valor a agregar.");
            txtValor.requestFocus();
            return;
        }

        Producto datos = new Producto();
        DAO_Producto funcion = new DAO_Producto();
        int valor = 0;
        int stock;

        datos.setCod_Producto(txtCod_Producto.getText());
        stock = Integer.parseInt(txtExistencia.getText());
        valor = Integer.parseInt(txtValor.getText());

        HistorialStock datos2 = new HistorialStock();
        DAO_HistorialStock funcion2 = new DAO_HistorialStock();
        datos2.setCod_ProductoFK(txtCod_Producto.getText());
        datos2.setId_UsuarioFK(Integer.parseInt(txtUsu.getText()));

        Calendar cal;
        int d, m, a;
        cal = dcFecha.getCalendar();
        d = cal.get(Calendar.DAY_OF_MONTH);
        m = cal.get(Calendar.MONTH);
        a = cal.get(Calendar.YEAR) - 1900;
        datos2.setFecha(new Date(a,m,d));

        datos2.setReferencia(JOptionPane.showInputDialog("Ingrese una referencia."));
        if (jrbAumentar.isSelected() == true) {
            datos2.setDescripcion("Agrego producto al stock.");
        } else {
            datos2.setDescripcion("Resto producto al stock.");
        }
        if (jrbDisminuir.isSelected() == true) {
            if (stock < valor) {
                JOptionPane.showMessageDialog(null, "Valor supera stock. ");
                txtValor.setText("");
                txtValor.requestFocus();
                return;
            }
        }

        datos2.setCantidad_Nva(Integer.parseInt(txtValor.getText()));
        if (funcion2.insertar(datos2)) {

            if (jrbAumentar.isSelected() == true) {
                stock = stock + valor;

                datos.setExistencia(stock);

                funcion.ModificarStockProductos(datos);
                JOptionPane.showMessageDialog(null, "Stock total del producto : " + stock);
                txtExistencia.setText(String.valueOf(stock));
            }

            if (jrbDisminuir.isSelected() == true) {
                if (stock >= valor) {
                    stock = stock - valor;
                    datos.setExistencia(stock);
                    funcion.ModificarStockProductos(datos);
                    JOptionPane.showMessageDialog(null, "Stock total del producto : " + stock);
                    txtExistencia.setText(String.valueOf(stock));
                }
            }
            txtValor.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "No se ingresaron datos al stock.");
        }
        mostrar(txtCod_Producto.getText());
    }//GEN-LAST:event_btnAceptarValoresActionPerformed

    private void txtUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuActionPerformed

    private void txtCod_ProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCod_ProductoFocusGained
        cambiarColorLinea(lineaCodigo);
    }//GEN-LAST:event_txtCod_ProductoFocusGained

    private void txtCod_ProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCod_ProductoFocusLost
        cambiarColorLineaDefecto();
    }//GEN-LAST:event_txtCod_ProductoFocusLost

    private void txtProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProveedorFocusGained
        cambiarColorLinea(lineaProveedor);
    }//GEN-LAST:event_txtProveedorFocusGained

    private void txtProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProveedorFocusLost
        cambiarColorLineaDefecto();
    }//GEN-LAST:event_txtProveedorFocusLost

    private void txtExistenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExistenciaFocusGained
        cambiarColorLinea(lineaExistencia);
    }//GEN-LAST:event_txtExistenciaFocusGained

    private void txtExistenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExistenciaFocusLost
        cambiarColorLineaDefecto();
    }//GEN-LAST:event_txtExistenciaFocusLost

    private void txtPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusGained
        cambiarColorLinea(lineaVenta);
    }//GEN-LAST:event_txtPrecioFocusGained

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        cambiarColorLineaDefecto();
    }//GEN-LAST:event_txtPrecioFocusLost

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        cambiarColorLinea(lineaValor);
    }//GEN-LAST:event_txtValorFocusGained

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        cambiarColorLineaDefecto();
    }//GEN-LAST:event_txtValorFocusLost

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        jPanelMinimizar.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        jPanelMinimizar.setBackground(new java.awt.Color(65,139,66));
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        this.setVisible(false);
        JPanelFrmStock obj = new JPanelFrmStock();
        obj.mostrar("");
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseEntered
        jPanelCerrar.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jLabelCerrarMouseEntered

    private void jLabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseExited
        jPanelCerrar.setBackground(new java.awt.Color(65,139,66));
    }//GEN-LAST:event_jLabelCerrarMouseExited

    public void cambiarColorLinea(JPanel panel) {
        lineaCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lineaProveedor.setBackground(new java.awt.Color(255, 255, 255));
        lineaExistencia.setBackground(new java.awt.Color(255, 255, 255));
        lineaVenta.setBackground(new java.awt.Color(255, 255, 255));
        lineaValor.setBackground(new java.awt.Color(153, 153, 153));
        panel.setBackground(new java.awt.Color(255, 50, 0));
    }
    
    public void cambiarColorLineaDefecto() {
        lineaCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lineaProveedor.setBackground(new java.awt.Color(255, 255, 255));
        lineaExistencia.setBackground(new java.awt.Color(255, 255, 255));
        lineaVenta.setBackground(new java.awt.Color(255, 255, 255));
        lineaValor.setBackground(new java.awt.Color(153, 153, 153));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorialStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarValores;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel btnMinimizar;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelMinimizar;
    private javax.swing.JPanel jPanelVerde;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabla;
    private javax.swing.JRadioButton jrbAumentar;
    private javax.swing.JRadioButton jrbDisminuir;
    private javax.swing.JPanel lineaCodigo;
    private javax.swing.JPanel lineaExistencia;
    private javax.swing.JPanel lineaProveedor;
    private javax.swing.JPanel lineaValor;
    private javax.swing.JPanel lineaVenta;
    public javax.swing.JTextField txtCod_Producto;
    public javax.swing.JTextField txtExistencia;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtProveedor;
    public javax.swing.JTextField txtUsu;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
