/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jose_Gonzalez
 */
public class FrmPrincipal extends javax.swing.JFrame {
static boolean menu;
    boolean desactivarVenta = false;
    boolean desactivarPersonal = false;
    boolean desactivarProducto = false;
    boolean desactivarInforme = false;
    boolean desactivarHerramienta = false;
    
    /**
     * Creates new form FrmPrincipal
    */
    
    CardLayout card;
    
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        card = (CardLayout) jPanelBranch.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMaster = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        icono = new javax.swing.JLabel();
        jPanelMVenta = new javax.swing.JPanel();
        JmIVentas = new javax.swing.JLabel();
        jPanelMPersonal = new javax.swing.JPanel();
        MenuPersonal = new javax.swing.JLabel();
        jPanelMProducto = new javax.swing.JPanel();
        MenuProductos = new javax.swing.JLabel();
        jPanelMInforme = new javax.swing.JPanel();
        MenuInformes = new javax.swing.JLabel();
        jPanelMHerramienta = new javax.swing.JPanel();
        MenuHerramientas = new javax.swing.JLabel();
        jPanelMSesion = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JLabel();
        lblId_Usuario = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jPanelMinimizar = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        jPanelCerrar = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JLabel();
        jPanelBranch = new javax.swing.JPanel();
        jPanelInicio = new javax.swing.JPanel();
        lblMsj = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Images/Principal/Icono.png")).getImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMaster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 139, 66)));
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/Logo.png"))); // NOI18N
        jPanelMenu.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 140));

        jPanelMVenta.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JmIVentas.setBackground(new java.awt.Color(255, 255, 255));
        JmIVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JmIVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JmIVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/ventaN.png"))); // NOI18N
        JmIVentas.setText("   Venta");
        JmIVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JmIVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JmIVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JmIVentasMouseExited(evt);
            }
        });
        jPanelMVenta.add(JmIVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        jPanelMenu.add(jPanelMVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 50));

        jPanelMPersonal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMPersonalMouseExited(evt);
            }
        });
        jPanelMPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPersonal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuPersonal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/usuarioN.png"))); // NOI18N
        MenuPersonal.setText("   Personal");
        MenuPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPersonalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuPersonalMouseExited(evt);
            }
        });
        jPanelMPersonal.add(MenuPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        jPanelMenu.add(jPanelMPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 50));

        jPanelMProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMProductoMouseExited(evt);
            }
        });
        jPanelMProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuProductos.setBackground(new java.awt.Color(255, 255, 255));
        MenuProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/productoN.png"))); // NOI18N
        MenuProductos.setText("   Productos");
        MenuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuProductosMouseExited(evt);
            }
        });
        jPanelMProducto.add(MenuProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        jPanelMenu.add(jPanelMProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 180, 50));

        jPanelMInforme.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMInforme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMInforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMInformeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMInformeMouseExited(evt);
            }
        });
        jPanelMInforme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuInformes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuInformes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/informeN.png"))); // NOI18N
        MenuInformes.setText("   Informes");
        MenuInformes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MenuInformesMouseMoved(evt);
            }
        });
        MenuInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuInformesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuInformesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuInformesMouseExited(evt);
            }
        });
        jPanelMInforme.add(MenuInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        jPanelMenu.add(jPanelMInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, 50));

        jPanelMHerramienta.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMHerramienta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMHerramientaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMHerramientaMouseExited(evt);
            }
        });
        jPanelMHerramienta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuHerramientas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MenuHerramientas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/herramientasN.png"))); // NOI18N
        MenuHerramientas.setText("   Herramientas");
        MenuHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHerramientasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuHerramientasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuHerramientasMouseExited(evt);
            }
        });
        jPanelMHerramienta.add(MenuHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        jPanelMenu.add(jPanelMHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 180, 50));

        jPanelMSesion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelMSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMSesionMouseExited(evt);
            }
        });
        jPanelMSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/cerrarN.png"))); // NOI18N
        btnCerrarSesion.setText("   Cerrar Sesión");
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });
        jPanelMSesion.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 50));

        jPanelMenu.add(jPanelMSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 180, 50));

        lblId_Usuario.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        lblId_Usuario.setText("CODIGO");
        jPanelMenu.add(lblId_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMaster.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 680));

        jPanelContent.setBackground(new java.awt.Color(255, 50, 0));
        jPanelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMinimizar.setBackground(new java.awt.Color(255, 50, 0));

        btnMinimizar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setText("_");
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMinimizarLayout = new javax.swing.GroupLayout(jPanelMinimizar);
        jPanelMinimizar.setLayout(jPanelMinimizarLayout);
        jPanelMinimizarLayout.setHorizontalGroup(
            jPanelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMinimizarLayout.setVerticalGroup(
            jPanelMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinimizarLayout.createSequentialGroup()
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanelContent.add(jPanelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 20, 18));

        jPanelCerrar.setBackground(new java.awt.Color(255, 50, 0));

        btnCerrar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCerrar.setText("X");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCerrarLayout = new javax.swing.GroupLayout(jPanelCerrar);
        jPanelCerrar.setLayout(jPanelCerrarLayout);
        jPanelCerrarLayout.setHorizontalGroup(
            jPanelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCerrarLayout.setVerticalGroup(
            jPanelCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelContent.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 20, 18));

        jPanelBranch.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBranch.setLayout(new java.awt.CardLayout());

        jPanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMsj.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblMsj.setText("¡ Bienvenid@ !");
        jPanelInicio.add(lblMsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblNombre.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        lblNombre.setText("NOMBRE");
        jPanelInicio.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblTipo.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        lblTipo.setText("TIPO USUARIO");
        jPanelInicio.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPanelBranch.add(jPanelInicio, "card2");

        jPanelContent.add(jPanelBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, 660));

        jPanelMaster.add(jPanelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 830, 680));

        getContentPane().add(jPanelMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(JFrame.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        jPanelMinimizar.setBackground(new java.awt.Color(50, 50, 50));
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        jPanelMinimizar.setBackground(new java.awt.Color(255, 50, 0));
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        jPanelCerrar.setBackground(new java.awt.Color(50, 50, 50));
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        jPanelCerrar.setBackground(new java.awt.Color(255, 50, 0));
    }//GEN-LAST:event_btnCerrarMouseExited

    private void JmIVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JmIVentasMouseEntered
        if (desactivarVenta) {
            
        } else {
            JmIVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/venta.png")));
            jPanelMVenta.setBackground(new java.awt.Color(102,102,102));
            JmIVentas.setForeground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_JmIVentasMouseEntered

    private void JmIVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JmIVentasMouseExited
        if (desactivarVenta) {
            
        } else {
            JmIVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/ventaN.png")));
            jPanelMVenta.setBackground(new java.awt.Color(255,255,255));
            JmIVentas.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_JmIVentasMouseExited

    private void jPanelMPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMPersonalMouseEntered
        
    }//GEN-LAST:event_jPanelMPersonalMouseEntered

    private void jPanelMPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMPersonalMouseExited
        ;
    }//GEN-LAST:event_jPanelMPersonalMouseExited

    private void jPanelMProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMProductoMouseEntered
        
    }//GEN-LAST:event_jPanelMProductoMouseEntered

    private void jPanelMProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMProductoMouseExited
        
    }//GEN-LAST:event_jPanelMProductoMouseExited

    private void jPanelMInformeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMInformeMouseEntered
        
    }//GEN-LAST:event_jPanelMInformeMouseEntered

    private void jPanelMInformeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMInformeMouseExited
        
    }//GEN-LAST:event_jPanelMInformeMouseExited

    private void jPanelMHerramientaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMHerramientaMouseEntered
        
    }//GEN-LAST:event_jPanelMHerramientaMouseEntered

    private void jPanelMHerramientaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMHerramientaMouseExited
       
    }//GEN-LAST:event_jPanelMHerramientaMouseExited

    private void jPanelMSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMSesionMouseEntered
        
    }//GEN-LAST:event_jPanelMSesionMouseEntered

    private void jPanelMSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMSesionMouseExited
        
    }//GEN-LAST:event_jPanelMSesionMouseExited

    private void JmIVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JmIVentasMouseClicked
        defaultMenu();
        cambiarColorBtn(jPanelMVenta, JmIVentas);
        JPanelFrmVenta panel = new JPanelFrmVenta();
        cambiarPanelContenedorBranch(panel,"Ventas");
        JPanelFrmVenta.txtCod_usuario.setText(lblId_Usuario.getText());
        JPanelFrmVenta.txtNombre_usuario.setText(lblNombre.getText());
        
        desactivarVenta = true;
        desactivarPersonal = false;
        desactivarProducto = false;
        desactivarInforme = false;
        desactivarHerramienta = false;
    }//GEN-LAST:event_JmIVentasMouseClicked

    private void MenuPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPersonalMouseClicked
        defaultMenu();
        cambiarColorBtn(jPanelMPersonal, MenuPersonal);
        JPanelFrmCliente panel = new JPanelFrmCliente();
        cambiarPanelContenedorBranch(panel,"Cliente");
        desactivarPersonal = true;
        desactivarVenta = false;
        desactivarProducto = false;
        desactivarInforme = false;
        desactivarHerramienta = false;
    }//GEN-LAST:event_MenuPersonalMouseClicked

    private void MenuPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPersonalMouseEntered
        if (desactivarPersonal) {
            
        } else {
            MenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/usuario.png")));
            jPanelMPersonal.setBackground(new java.awt.Color(102,102,102));
            MenuPersonal.setForeground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_MenuPersonalMouseEntered

    private void MenuPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPersonalMouseExited
        if (desactivarPersonal) {
            
        } else {
            MenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/usuarioN.png")));
            jPanelMPersonal.setBackground(new java.awt.Color(255,255,255));
            MenuPersonal.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_MenuPersonalMouseExited

    private void MenuProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProductosMouseClicked
        if (menu) {
            defaultMenu();
            cambiarColorBtn(jPanelMProducto, MenuProductos);
            JPanelFrmConsultaStock panel = new JPanelFrmConsultaStock();
            cambiarPanelContenedorBranch(panel,"ConsultaStock");
        } else {
            defaultMenu();
            cambiarColorBtn(jPanelMProducto, MenuProductos);
            JPanelFrmProductos panel = new JPanelFrmProductos();
            cambiarPanelContenedorBranch(panel,"Productos");
        }
        desactivarProducto = true;
        desactivarVenta = false;
        desactivarPersonal = false;
        desactivarInforme = false;
        desactivarHerramienta = false;
    }//GEN-LAST:event_MenuProductosMouseClicked

    private void MenuInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInformesMouseClicked
        defaultMenu();
        cambiarColorBtn(jPanelMInforme, MenuInformes);
        JPanelRptVentasporFecha panel = new JPanelRptVentasporFecha();
        cambiarPanelContenedorBranch(panel,"Informes");
        desactivarInforme = true;
        desactivarVenta = false;
        desactivarPersonal = false;
        desactivarProducto = false;
        desactivarHerramienta = false;
    }//GEN-LAST:event_MenuInformesMouseClicked

    private void MenuHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHerramientasMouseClicked
        if (menu) {
            defaultMenu();
            cambiarColorBtn(jPanelMHerramienta, MenuHerramientas);
            JPanelFrmDolar panel = new JPanelFrmDolar();
            cambiarPanelContenedorBranch(panel,"Dolar");
        } else {
            defaultMenu();
            cambiarColorBtn(jPanelMHerramienta, MenuHerramientas);
            JPanelFrmConsultarVentas panel = new JPanelFrmConsultarVentas();
            cambiarPanelContenedorBranch(panel,"ConsultarVentas");
        }
        desactivarHerramienta = true;
        desactivarVenta = false;
        desactivarPersonal = false;
        desactivarProducto = false;
        desactivarInforme = false;
    }//GEN-LAST:event_MenuHerramientasMouseClicked

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        FrmLogin form = new FrmLogin();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void MenuProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProductosMouseEntered
        if (desactivarProducto) {
            
        } else {
            MenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/producto.png")));
            jPanelMProducto.setBackground(new java.awt.Color(102,102,102));
            MenuProductos.setForeground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_MenuProductosMouseEntered

    private void MenuProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProductosMouseExited
        if (desactivarProducto) {
            
        } else {
            MenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/productoN.png")));
            jPanelMProducto.setBackground(new java.awt.Color(255,255,255));
            MenuProductos.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_MenuProductosMouseExited

    private void MenuInformesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInformesMouseEntered
        if (desactivarInforme) {
            
        } else {
            MenuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/informe.png")));
            jPanelMInforme.setBackground(new java.awt.Color(102,102,102));
            MenuInformes.setForeground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_MenuInformesMouseEntered

    private void MenuInformesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInformesMouseMoved
        
    }//GEN-LAST:event_MenuInformesMouseMoved

    private void MenuHerramientasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHerramientasMouseEntered
        if (desactivarHerramienta) {
            
        } else {
            MenuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/herramientas.png")));
            jPanelMHerramienta.setBackground(new java.awt.Color(102,102,102));
            MenuHerramientas.setForeground(new java.awt.Color(255,255,255));
        }
    }//GEN-LAST:event_MenuHerramientasMouseEntered

    private void MenuHerramientasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHerramientasMouseExited
        if (desactivarHerramienta) {
            
        } else {
            MenuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/herramientasN.png")));
            jPanelMHerramienta.setBackground(new java.awt.Color(255,255,255));
            MenuHerramientas.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_MenuHerramientasMouseExited

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/cerrar.png")));
        jPanelMSesion.setBackground(new java.awt.Color(102,102,102));
        btnCerrarSesion.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/cerrarN.png")));
        jPanelMSesion.setBackground(new java.awt.Color(255,255,255));
        btnCerrarSesion.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void MenuInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInformesMouseExited
        if (desactivarInforme) {
            
        } else {
            MenuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/informeN.png")));
            jPanelMInforme.setBackground(new java.awt.Color(255,255,255));
            MenuInformes.setForeground(new java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_MenuInformesMouseExited

    
    public void cambiarPanelContenedorBranch(JPanel panel, String name) {
        jPanelBranch.add(panel, name);
        card.show(jPanelBranch, name);
    }
    
    public void cambiarColorBtn(JPanel panel, JLabel btn) {
        panel.setBackground(new java.awt.Color(204,204,204));
        btn.setForeground(new java.awt.Color(255, 50, 0));
    }
    
    public void defaultMenu(){
        JmIVentas.setForeground(new java.awt.Color(0, 0, 0));
        MenuPersonal.setForeground(new java.awt.Color(0, 0, 0));
        MenuProductos.setForeground(new java.awt.Color(0, 0, 0));
        MenuInformes.setForeground(new java.awt.Color(0, 0, 0));
        MenuHerramientas.setForeground(new java.awt.Color(0, 0, 0));
        jPanelMVenta.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMPersonal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMInforme.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMHerramienta.setBackground(new java.awt.Color(255, 255, 255));
        JmIVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/ventaN.png")));
        MenuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/usuarioN.png")));
        MenuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/productoN.png")));
        MenuInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/informeN.png")));
        MenuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/herramientasN.png")));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Principal/cerrarN.png")));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JmIVentas;
    private javax.swing.JLabel MenuHerramientas;
    private javax.swing.JLabel MenuInformes;
    private javax.swing.JLabel MenuPersonal;
    private javax.swing.JLabel MenuProductos;
    public javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel icono;
    public static javax.swing.JPanel jPanelBranch;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMHerramienta;
    private javax.swing.JPanel jPanelMInforme;
    private javax.swing.JPanel jPanelMPersonal;
    private javax.swing.JPanel jPanelMProducto;
    private javax.swing.JPanel jPanelMSesion;
    private javax.swing.JPanel jPanelMVenta;
    private javax.swing.JPanel jPanelMaster;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMinimizar;
    public static javax.swing.JLabel lblId_Usuario;
    public static javax.swing.JLabel lblMsj;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
