/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Connection.DB_Manager;
import DAO.DAO_Configuracion;
import java.awt.CardLayout;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jose_Gonzalez
 */
public class JPanelRptVentasporAlmacen extends javax.swing.JPanel {

    DB_Manager db_manager;
    Connection connection;

    public static int comprobarCompras;
    
    /**
     * Creates new form JPanelRptVentasporAlmacen
     */
    CardLayout card;
    
    public JPanelRptVentasporAlmacen() {
        initComponents();
        
        cambiarColorBtn(jPanelRecaudacionAlmacen, btnRecaudacionAlmacen);
        
        card = (CardLayout) FrmPrincipal.jPanelBranch.getLayout();
        
        db_manager = new DB_Manager();
        connection = db_manager.getConnection();
    }
    
    public void cambiarColorBtn(JPanel panel, JLabel btn) {
        panel.setBackground(new java.awt.Color(204, 204, 204));
        btn.setForeground(new java.awt.Color(255, 50, 0));
    }
    
    public void cambiarPanelContenedorBranch(JPanel panel, String name) {
        FrmPrincipal.jPanelBranch.add(panel, name);
        card.show(FrmPrincipal.jPanelBranch, name);
    }
    
    public void cambiarColorMenu(JPanel panel, JLabel btn) {
        panel.setBackground(new java.awt.Color(102, 102, 102));
        btn.setForeground(new java.awt.Color(255, 255, 255));
    }
    
    public void cambiarColorMenuDefecto(JPanel panel, JLabel btn) {
        panel.setBackground(new java.awt.Color(255, 255, 255));
        btn.setForeground(new java.awt.Color(0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        dcFecha_Inicio = new com.toedter.calendar.JDateChooser();
        dcFecha_termino = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanelVentaFecha = new javax.swing.JPanel();
        btnVentasporFecha = new javax.swing.JLabel();
        jPanelVentaproductosFecha = new javax.swing.JPanel();
        btnVentaProductosFecha = new javax.swing.JLabel();
        jPanelRecaudacionAlmacen = new javax.swing.JPanel();
        btnRecaudacionAlmacen = new javax.swing.JLabel();
        jPanelModificacionStock = new javax.swing.JPanel();
        btnHistorialStock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 139, 66)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 139, 66)));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Views/acceso.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, -1));

        dcFecha_Inicio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(dcFecha_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 30));

        dcFecha_termino.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(dcFecha_termino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setText("Inicio :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText("Termino :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(65, 139, 66));
        jLabel10.setText("VENTAS POR ALMACÉN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVentaFecha.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentaFecha.setPreferredSize(new java.awt.Dimension(130, 50));

        btnVentasporFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVentasporFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVentasporFecha.setText("Ventas por Fecha");
        btnVentasporFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentasporFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasporFechaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasporFechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasporFechaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentaFechaLayout = new javax.swing.GroupLayout(jPanelVentaFecha);
        jPanelVentaFecha.setLayout(jPanelVentaFechaLayout);
        jPanelVentaFechaLayout.setHorizontalGroup(
            jPanelVentaFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVentasporFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVentaFechaLayout.setVerticalGroup(
            jPanelVentaFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVentasporFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanelVentaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 50));

        jPanelVentaproductosFecha.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentaproductosFecha.setPreferredSize(new java.awt.Dimension(130, 50));

        btnVentaProductosFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnVentaProductosFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVentaProductosFecha.setText("Venta Productos por Fecha");
        btnVentaProductosFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentaProductosFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentaProductosFechaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentaProductosFechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentaProductosFechaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentaproductosFechaLayout = new javax.swing.GroupLayout(jPanelVentaproductosFecha);
        jPanelVentaproductosFecha.setLayout(jPanelVentaproductosFechaLayout);
        jPanelVentaproductosFechaLayout.setHorizontalGroup(
            jPanelVentaproductosFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaproductosFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVentaProductosFecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVentaproductosFechaLayout.setVerticalGroup(
            jPanelVentaproductosFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaproductosFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVentaProductosFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanelVentaproductosFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 210, 50));

        jPanelRecaudacionAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRecaudacionAlmacen.setPreferredSize(new java.awt.Dimension(130, 50));

        btnRecaudacionAlmacen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRecaudacionAlmacen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecaudacionAlmacen.setText("Recaudación por Almacén");
        btnRecaudacionAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecaudacionAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecaudacionAlmacenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecaudacionAlmacenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecaudacionAlmacenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelRecaudacionAlmacenLayout = new javax.swing.GroupLayout(jPanelRecaudacionAlmacen);
        jPanelRecaudacionAlmacen.setLayout(jPanelRecaudacionAlmacenLayout);
        jPanelRecaudacionAlmacenLayout.setHorizontalGroup(
            jPanelRecaudacionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecaudacionAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRecaudacionAlmacen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRecaudacionAlmacenLayout.setVerticalGroup(
            jPanelRecaudacionAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecaudacionAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRecaudacionAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanelRecaudacionAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 200, 50));

        jPanelModificacionStock.setBackground(new java.awt.Color(255, 255, 255));
        jPanelModificacionStock.setPreferredSize(new java.awt.Dimension(130, 50));

        btnHistorialStock.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHistorialStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHistorialStock.setText("Historial de Modificación Stock");
        btnHistorialStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialStockMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelModificacionStockLayout = new javax.swing.GroupLayout(jPanelModificacionStock);
        jPanelModificacionStock.setLayout(jPanelModificacionStockLayout);
        jPanelModificacionStockLayout.setHorizontalGroup(
            jPanelModificacionStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificacionStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHistorialStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelModificacionStockLayout.setVerticalGroup(
            jPanelModificacionStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificacionStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHistorialStock, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanelModificacionStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 240, 50));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        try {
            JasperReport jr = (JasperReport) JRLoader.loadObject(VistaReporte.class.getResource("/Report/reportePorCategorias.jasper"));

            String ruta = System.getProperty("user.dir");
            ruta += "\\src\\Images\\Report\\Logo (Gris, Actual).png";
            System.out.println("PATH: " + ruta);

            HashMap<String, Object> parametro = new HashMap<>();
            parametro.put("path", ruta);

            DAO_Configuracion funcion = new DAO_Configuracion();
            float dolar = funcion.getValueDollar();
            parametro.put("dolar", dolar);

            parametro.put("fecha_inicio", dcFecha_Inicio.getDate());
            parametro.put("fecha_termino", dcFecha_termino.getDate());

            JasperPrint jp = JasperFillManager.fillReport(jr, parametro, connection);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVentasporFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasporFechaMouseClicked
        JPanelRptVentasporFecha panel = new JPanelRptVentasporFecha();
        cambiarPanelContenedorBranch(panel, "VentasFecha");
    }//GEN-LAST:event_btnVentasporFechaMouseClicked

    private void btnVentasporFechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasporFechaMouseEntered
        cambiarColorMenu(jPanelVentaFecha, btnVentasporFecha);
    }//GEN-LAST:event_btnVentasporFechaMouseEntered

    private void btnVentasporFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasporFechaMouseExited
        cambiarColorMenuDefecto(jPanelVentaFecha, btnVentasporFecha);
    }//GEN-LAST:event_btnVentasporFechaMouseExited

    private void btnVentaProductosFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaProductosFechaMouseClicked
        JPanelRptVentasProductosporFecha panel = new JPanelRptVentasProductosporFecha();
        cambiarPanelContenedorBranch(panel, "VentasProductoFecha");
    }//GEN-LAST:event_btnVentaProductosFechaMouseClicked

    private void btnVentaProductosFechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaProductosFechaMouseEntered
       cambiarColorMenu(jPanelVentaproductosFecha, btnVentaProductosFecha);
    }//GEN-LAST:event_btnVentaProductosFechaMouseEntered

    private void btnVentaProductosFechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaProductosFechaMouseExited
        cambiarColorMenuDefecto(jPanelVentaproductosFecha, btnVentaProductosFecha);
    }//GEN-LAST:event_btnVentaProductosFechaMouseExited

    private void btnRecaudacionAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecaudacionAlmacenMouseClicked
       
    }//GEN-LAST:event_btnRecaudacionAlmacenMouseClicked

    private void btnRecaudacionAlmacenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecaudacionAlmacenMouseEntered
       
    }//GEN-LAST:event_btnRecaudacionAlmacenMouseEntered

    private void btnRecaudacionAlmacenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecaudacionAlmacenMouseExited
       
    }//GEN-LAST:event_btnRecaudacionAlmacenMouseExited

    private void btnHistorialStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialStockMouseClicked
        try {
            
            String ruta = System.getProperty("user.dir");
            ruta += "\\src\\Images\\Report\\Logo (Gris, Actual).png";
            System.out.println("PATH: " + ruta);
            HashMap<String, Object> map = new HashMap<>();
            map.put("path", ruta);

            JasperReport jr = (JasperReport) JRLoader.loadObject(VistaReporte.class.getResource("/Report/RptHistorial.jasper"));
            JasperPrint jp = JasperFillManager.fillReport(jr, map, connection);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }//GEN-LAST:event_btnHistorialStockMouseClicked

    private void btnHistorialStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialStockMouseEntered
        cambiarColorMenu(jPanelModificacionStock, btnHistorialStock);
    }//GEN-LAST:event_btnHistorialStockMouseEntered

    private void btnHistorialStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialStockMouseExited
        cambiarColorMenuDefecto(jPanelModificacionStock, btnHistorialStock);
    }//GEN-LAST:event_btnHistorialStockMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel btnHistorialStock;
    private javax.swing.JLabel btnRecaudacionAlmacen;
    private javax.swing.JLabel btnVentaProductosFecha;
    private javax.swing.JLabel btnVentasporFecha;
    private com.toedter.calendar.JDateChooser dcFecha_Inicio;
    private com.toedter.calendar.JDateChooser dcFecha_termino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelModificacionStock;
    private javax.swing.JPanel jPanelRecaudacionAlmacen;
    private javax.swing.JPanel jPanelVentaFecha;
    private javax.swing.JPanel jPanelVentaproductosFecha;
    // End of variables declaration//GEN-END:variables
}
